name: miruryoiki
description: "Flutter desktop application designed to track and manage local media files."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.0.0
  provider: ^6.0.3
  win32: ^5.12.0
  path: ^1.8.2
  file_picker: ^10.1.2
  window_size: ^0.1.0
  path_provider: ^2.1.5
  open_app_file: ^4.0.2
  flutter_dotenv: ^5.2.1
  graphql: ^5.2.1
  oauth2: ^2.0.3
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  url_launcher: ^6.3.1
  smooth_scroll_multiplatform: ^1.0.8
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - .env
    
  # fonts:
  #   - family: 
  #     fonts:
  #       - asset: fonts/Regular.ttf
  #       - asset: fonts/Italic.ttf
  #         style: italic
  #   - family: 
  #     fonts:
  #       - asset: fonts/Regular.ttf
  #       - asset: fonts/Bold.ttf
  #         weight: 700