name: miruryoiki
description: "Flutter desktop application designed to track and manage local media files."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.0.0
  provider: ^6.0.3
  win32: ^5.12.0
  path: ^1.8.2
  file_picker: ^10.1.2
  window_size: ^0.1.0
  path_provider: ^2.1.5
  open_app_file: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: false

  # assets:

  # fonts:
  #   - family: 
  #     fonts:
  #       - asset: fonts/Regular.ttf
  #       - asset: fonts/Italic.ttf
  #         style: italic
  #   - family: 
  #     fonts:
  #       - asset: fonts/Regular.ttf
  #       - asset: fonts/Bold.ttf
  #         weight: 700