name: miruryoiki
description: "Flutter desktop application designed to track and manage local media files."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.11.5
  provider: ^6.0.3
  win32: ^5.12.0
  path: ^1.8.2
  file_picker: ^10.1.2
  window_size: ^0.1.0
  path_provider: ^2.1.5
  open_app_file: ^4.0.2
  flutter_dotenv: ^5.2.1
  graphql: ^5.2.1
  oauth2: ^2.0.3
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  url_launcher: ^6.3.1
  smooth_scroll_multiplatform:
    path: M:/Projects/dyn_mouse_scroll/
  app_links: ^6.4.0
  flutter_acrylic: ^1.1.4
  system_theme: ^3.1.2
  window_manager: ^0.5.1
  open_file: ^3.5.10
  shared_preferences: ^2.5.3
  recase: ^4.1.0
  palette_generator: ^0.3.3+3
  google_fonts: ^6.2.1
  jovial_svg: ^1.1.25
  bitsdojo_window: ^0.1.6
  toggle_switch: ^2.3.0
  crypto: ^3.0.6
  win32_registry: ^2.1.0
  transparent_image: ^2.0.1
  defer_pointer: ^0.0.2
  collection: ^1.19.1
  ffi: ^2.1.4
  logger: ^2.5.0
  synchronized: ^3.3.0+3
  material_symbols_icons: ^4.2815.0
  flutter_custom_cursor: ^0.0.4
  intl: ^0.19.0
  image: any
  video_data_utils:
    path: M:/Projects/video_data_utils/
    # git:
      # url: https://github.com/LordLux/video_data_utils.git
  flutter_desktop_context_menu:
    path: M:/Projects/flutter_desktop_context_menu/
    # git:
    #   url: https://github.com/LordLux/flutter_desktop_context_menu.git
  cached_network_image: ^3.3.1
  animated_flip_counter: ^0.3.4
  pie_chart: ^5.4.0
  flexible_wrap: ^1.0.6
  flutter_html: ^3.0.0
  connectivity_plus: ^6.0.5
  flutter_html_iframe: ^3.0.0
  webview_windows: ^0.4.0
  flutter_html_video: ^3.0.0
  flutter_heatmap_calendar: ^1.0.5
  package_info_plus: ^8.3.0
  args: ^2.7.0
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  md5_file_checksum: ^1.1.0
  json_annotation: ^4.8.1
  scrollable_positioned_list: ^0.3.8
  flutter_single_instance: ^1.6.0 # TODO https://pub.dev/packages/flutter_single_instance#macos
  shimmer: ^3.0.0
  sticky_headers:
    path: M:/Projects/flutter_expandable_sticky_headers/
    # git:
    #   url: https://github.com/LordLux/flutter_expandable_sticky_headers.git
  squiggly_slider:
    path: M:/Projects/squiggly_slider/
  flutter_svg: ^2.2.1
  process_monitor:
    path: M:/Projects/process_monitor/
  glossy: ^0.0.5
  flutter_anitomy:
    path: M:/Projects/flutter_anitomy/

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.14.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  build_runner: ^2.4.7
    
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - .env
    
  ### Anilist:
    - assets/icons/anilist/logo.png
    - assets/icons/anilist/logo.si
    - assets/icons/anilist/offline.si
    - assets/icons/anilist/offline_logo.si
    
  ### System Icons:
    - assets/system/icon.ico
    - assets/system/icon.png
    
    # Cursors:
    - assets/system/cursors/grab.png
    - assets/system/cursors/grabbing.png
    
    # Context Menu:
    - assets/system/context/anilist.png
    - assets/system/context/check.png
    - assets/system/context/check_all.png
    - assets/system/context/copy.ico
    - assets/system/context/folder_info.ico
    - assets/system/context/folder_open.ico
    - assets/system/context/hide.ico
    - assets/system/context/list.png
    - assets/system/context/play.png
    - assets/system/context/series.ico
    - assets/system/context/unhide.ico
    - assets/system/context/unwatch.ico
    - assets/system/context/video_info.ico
    - assets/system/context/watch.png
    - assets/system/context/watch_all.ico
    
    # Video Players:
    - assets/system/players/
    - assets/system/players/vlc.si
    - assets/system/players/mpchc.si
    
  ### Images:
    - assets/images/noise.png


  # fonts:
  #   - family: 
  #     fonts:
  #       - asset: fonts/Regular.ttf
  #       - asset: fonts/Italic.ttf
  #         style: italic
  #   - family: 
  #     fonts:
  #       - asset: fonts/Regular.ttf
  #       - asset: fonts/Bold.ttf
  #         weight: 700
flutter_launcher_icons:
  image_path: "assets/system/icon.png"
  windows:
    generate: true
    image_path: "assets/system/icon.png"
    icon_size: 128 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/system/icon.png"