#import "../common/fragments.graphql"

# OVERVIEW TAB
query GetAnimeOverview($id: Int!) {
  # Anime Media
  Media(id: $id, type: ANIME) {
    ...AnimeOverview
    
    # Stats
    stats {
      statusDistribution { status amount }
      scoreDistribution { score amount }
    }

    # Relations
    relations {
      edges {
        id
        relationType(version: 2)
        node {
          ...AnimeCard
        }
      }
    }

    # Characters Preview
    characterPreview: characters(perPage: 6, sort: [ROLE, RELEVANCE, ID]) {
      edges {
        id
        role
        name
        voiceActors(language: JAPANESE, sort: [RELEVANCE, ID]) {
          ...StaffCard
        }
        node {
          ...CharacterCard
        }
      }
    }

    # Staff Preview
    staffPreview: staff(perPage: 4, sort: [RELEVANCE, ID]) {
      edges {
        id
        role
        node {
          ...StaffCard
        }
      }
    }

    # Studios
    studios {
      edges {
        isMain
        node {
          id
          name
        }
      }
    }

    # # Review Preview
    # reviewPreview: reviews(perPage: 2, sort: [RATING_DESC, ID]) {
    #   pageInfo {
    #     total
    #   }
    #   nodes {
    #     id
    #     summary
    #     rating
    #     ratingAmount
    #     user {
    #       ...UserAvatar
    #     }
    #   }
    # }

    # Recommendations Preview
    recommendations(perPage: 7, sort: [RATING_DESC, ID]) {
      pageInfo {
        total
      }
      nodes {
        id
        rating
        userRating
        mediaRecommendation {
          ...AnimeCard
        }
        user {
          ...UserAvatar
        }
      }
    }
    
    # External Links
    externalLinks {
      id site url type language color icon notes isDisabled
    }
  }

  # Following who are watching this
  Page(perPage: 8) {
    pageInfo {
      total
      perPage
      currentPage
      lastPage
      hasNextPage
    }
    mediaList(mediaId: $id, isFollowing: true, sort: [UPDATED_TIME_DESC]) {
      id
      status
      score
      progress
      user {
        id
        name
        avatar {
          large
        }
        mediaListOptions {
          scoreFormat
        }
      }
    }
  }
}

query GetMultipleAnimeDetails($ids: [Int]) {
  Page(perPage: 50) {
    media(id_in: $ids, type: ANIME) {
      ...AnimeCard
      bannerImage
      description
      endDate {
        year
        month
        day
      }
      genres
      trending
      favourites
      updatedAt
      siteUrl
      rankings {
        id
        rank
        type
        format
        year
        season
        allTime
        context
      }
    }
  }
}

# CHARACTERS TAB
query GetAnimeCharacters($id: Int!, $page: Int) {
  Media(id: $id, type: ANIME) {
    id
    characters(page: $page, perPage: 25, sort: [ROLE, RELEVANCE, ID]) {
      pageInfo {
        total perPage currentPage lastPage hasNextPage
      }
      edges {
        id
        role
        name
        node { ...CharacterCard }
        voiceActors(language: JAPANESE, sort: [RELEVANCE, ID]) {
          ...StaffCard
        }
      }
    }
  }
}

# STAFF TAB
query GetAnimeStaff($id: Int!, $page: Int) {
  Media(id: $id, type: ANIME) {
    id
    staff(page: $page, perPage: 25, sort: [RELEVANCE, ID]) {
      pageInfo {
        total perPage currentPage lastPage hasNextPage
      }
      edges {
        id
        role
        node { ...StaffCard }
      }
    }
  }
}

# FOLLOWING TAB
query GetAnimeSocial($id: Int!, $page: Int) {
  Page(page: $page, perPage: 25) {
    pageInfo {
      total perPage currentPage lastPage hasNextPage
    }
    mediaList(mediaId: $id, isFollowing: true, sort: [UPDATED_TIME_DESC]) {
      id
      status
      score(format: POINT_10)
      updatedAt
      user { ...UserAvatar }
    }
  }
}

# STATS TAB
query GetAnimeStats($id: Int!) {
  Media(id: $id, type: ANIME) {
    id
    stats {
      statusDistribution {
        status
        amount
      }
      scoreDistribution {
        score
        amount
      }
    }
    trends(sort: EPISODE_DESC, perPage: 25) {
      nodes {
        date
        episode
        averageScore   # Replaces airingProgression.score
        inProgress     # Replaces airingProgression.watching
        trending
        popularity
      }
    }
  }
}